motd=§lWeisonty §4Anarchy §r| §7Bedrock 1.19.51
server-port=19132
server-portv6=19133
enable-ipv6=off
white-list=off
max-players=100
gamemode=0
force-gamemode=off
hardcore=off
pvp=on
difficulty=3
generator=normal
level-name=world
level-seed=
level-type=DEFAULT
enable-query=on
enable-rcon=off
rcon.password=change_me_now
auto-save=on
view-distance=8
spawn-protection=0
max-world-size=29999984
online-mode=off
xbox-auth=off
language=eng
